feat: troubleshooting page search
vtexdocs/helpcenter pull request #132
Opened 2024-10-28 12:40 UTC by phvm

#### What is the purpose of this pull request?

Implement a search bar for the troubleshooting page

#### What problem is this solving?

Other cards list pages have a search bar except the troubleshooting one

#### How should this be manually tested?

#### Screenshots or example usage

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2024-12-04 22:10 UTC, PedroAntunesCosta requested changes
I am going too fix the tags in the content repo. Then we'll be able to test this properly.

2024-12-04 22:10 UTC, PedroAntunesCosta commented on src/components/troubleshooting-card/index.tsx
> +  productTeam,
This is really suposed to be `tags`. In the current help-center-content state we must still run the script that puts them into the frontmatter. Then they'll be rendered.

2024-12-04 22:10 UTC, PedroAntunesCosta commented on src/pages/troubleshooting/index.tsx
> +          filters.length === 0 || filters.includes(troubleshoot.productTeam)
This is suposed to work with the tags.

2024-12-04 22:10 UTC, PedroAntunesCosta commented on src/pages/troubleshooting/index.tsx
> +              productTeam: String(frontmatter.productTeam),
Tags here too.

2024-12-04 22:10 UTC, PedroAntunesCosta commented on src/utils/constants.ts
> +      {
I am going to try and generate a list with the script that rearranges the tags. But for now we can use a manual approximation, even if we don't check every article.

2024-12-04 22:10 UTC, PedroAntunesCosta commented on src/utils/typings/types.ts
> +  productTeam: string
Tags here too.

2024-12-11 22:33 UTC, julia-rabello commented
I reverted the commits that replaced tags with product team and the tags seem to be working properly now.

<img width="611" alt="image" src="https://github.com/user-attachments/assets/9a67fae5-b6e9-4738-aa16-b40c7573805c" />

However, the filters are influenced by the values in constants.ts. Since they're not really constants (they depend on the content of markdown files), we need to get these values from help-center-content troubleshooting files. I'm not sure how to generate that list dynamically, and add localization as well (tags are different depending on the language). Do you have any idea how to do that? @PedroAntunesCosta 

Should we remove filters while this is not ready? Or just have a static list based on troubleshooting guides so far?

2024-12-11 23:15 UTC, PedroAntunesCosta requested changes
It works! But I think we should create a static list for the filters. I have some more considerations on this:
- Would all tags be too many for the filter picking UI?
- If so, should we list only products? I feel like this is not the way knowledge should be organized in troubleshooting, but it might help.

2024-12-17 16:04 UTC, PedroAntunesCosta approved these changes

2024-12-17 17:57 UTC, merged