Feat/footer
vtexdocs/helpcenter pull request #21
Opened 2023-12-21 19:12 UTC by Pvcunha

#### What is the purpose of this pull request?

Creates the new footer and its needs.
1. New social media icons
2. New site map link
3. New language switcher for footer

#### How should this be manually tested?

Run ```$ yarn run dev ``` and try for the following resolutions: 360, 640, 832, 1280, 1920

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2023-12-22 13:36 UTC, aliceoq approved these changes
LGTM 

Uma coisa que pode mudar depois é pra o dropdown fechar depois de selecionar a linguagem.

2024-01-02 12:42 UTC, ThayllyR commented
LGTM. 
Falta somente acrescentar a animação de hoover nas redes sociais. Se possível deixar a opacidade mais clara como no protótipo. Mas está muito bom, parabéns!

2024-01-02 23:48 UTC, RobsonOlv requested changes
Tá ótimo, parabéns! Só esse detalhe em aberto

2024-01-02 23:48 UTC, RobsonOlv commented on src/components/footer/styles.ts
> +const test: SxStyleProp = {
Notei que esse estilo `test` não está sendo usado. Caso esteja, acharia válido renomear

2024-01-03 14:01 UTC, Pvcunha commented on src/components/footer/styles.ts
> +const test: SxStyleProp = {
Passou batido, era pra ter sido deletado

2024-01-03 14:42 UTC, RobsonOlv approved these changes
LGTM :rocket: :clap:

2024-01-09 19:55 UTC, merged

2024-01-10 18:21 UTC, ThayllyR reviewed
LGTM ✨