Feat/known issues
vtexdocs/helpcenter pull request #26
Opened 2024-01-24 13:51 UTC by aliceoq

#### What is the purpose of this pull request?

#### What problem is this solving?

#### How should this be manually tested?

#### Screenshots or example usage

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2024-01-26 13:54 UTC, Pvcunha approved these changes
LGTM!

2024-01-26 14:20 UTC, ThayllyR commented
Muito bom! ✨

2024-01-26 14:21 UTC, ThayllyR approved these changes
LGTM ✨

2024-01-31 11:18 UTC, Pvcunha requested changes

2024-01-31 11:18 UTC, Pvcunha commented on src/pages/known-issues/[slug].tsx
> +                      <em>Criado em </em>
Ta em português independente da linguagem selecionada

2024-01-31 11:18 UTC, Pvcunha commented on src/pages/known-issues/[slug].tsx
> +                      <em>Atualizado em </em>
Aqui também, está sem localização de idioma

2024-01-31 12:04 UTC, Pvcunha approved these changes
LGTM!

2024-01-31 20:29 UTC, ThayllyR approved these changes
✅✨

2024-02-01 01:58 UTC, RobsonOlv commented on src/components/filter/index.tsx
> +  const FilterModal = () => {
Talvez seja interessante adicionar o hook  `useClickOutside` aqui:
```
  const modalRef = useRef<HTMLDivElement>()
  useClickOutside(modalRef, () => setIsModalOpen(false))
  ...
  <Box ref={modalRef} sx={styles.container}>
  ...
```
Somente para melhorar a experiência do usuário

2024-02-01 01:59 UTC, RobsonOlv approved these changes
LGTM :rocket:

2024-02-01 11:55 UTC, aliceoq commented on src/components/filter/index.tsx
> +  const FilterModal = () => {
Não usei o useClickOutside, mas coloquei pro clique fora do modal fechar 🫡

2024-02-01 12:00 UTC, merged