Feat/tutorials
vtexdocs/helpcenter pull request #31
Opened 2024-02-07 22:14 UTC by Pvcunha

#### What is the purpose of this pull request?

Cria páginas de tutoriais & soluções seguindo o protótipo de alta fidelidade.

#### What problem is this solving?

* Adiciona páginas de índice como no protótipo de alta fidelidade
* Botão de paginação "next" não cobre toda a largura do componente quando está sozinho.

#### How should this be manually tested?

1. Navegue para a página de Tutorial & solutions
2. Selecione na sidebar dentre os itens: Beta, Subscription Beta (primeiro filho de beta) ou qualquer documento e compare com o [protótipo de alta fidelidade](https://www.figma.com/file/ucTW25mSmAeYSm7IREga4o/Prot%C3%B3tipo-de-Alta-fidelidade-%7C-Help-Center?type=design&node-id=191-28505&mode=design&t=zsZVcsueriZeu3Pv-0).

**Como o navigation ainda precisa ser atualizado, apenas esses dois itens estão configurados para funcionar como índices e o restante ainda se comporta normalmente.**

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2024-02-08 15:34 UTC, ThayllyR commented
Está ótimo, Pedro. Só uma questão que seria interessante revisar é o botão de previous e next no mobile. Que tá bem cortado. O restante está exatamento como no protótipo. Muito bom! ✨

2024-02-08 15:35 UTC, ThayllyR commented
Isso está acontecendo em alguns. Mas outros estão ok.

2024-02-08 15:36 UTC, ThayllyR approved these changes
LGTM ✨ Ficou ótimo!

2024-02-08 18:05 UTC, ThayllyR commented
Agora tá certinho o card! Bom trabalho, Pedro! ✨🧑🏻‍💻

2024-02-08 18:10 UTC, ThayllyR approved these changes
LGTM ✨

2024-02-09 17:04 UTC, aliceoq approved these changes
LGTM

2024-02-15 17:42 UTC, ThayllyR approved these changes
LGTM ✨

2024-02-20 17:12 UTC, RobsonOlv approved these changes
LGTM :rocket:

2024-02-20 19:43 UTC, ThayllyR requested changes
O erro é ao clicar. Quando clica no link vigente (na página que o usuário está) e o usuário clica no nome não fecha, só na seta.

2024-02-23 13:06 UTC, ThayllyR approved these changes

2024-02-23 13:25 UTC, merged