Add copy link button to documentation pages
vtexdocs/helpcenter pull request #71
Opened 2024-06-19 22:47 UTC by Icaro-Nunes

#### What is the purpose of this pull request?

Create a Copy Link Button component and add to the article pages (start here, tutorials and solutions, known issues, FAQ).

#### What problem is this solving?

Issue #54.

#### How should this be manually tested?

Check articles in the start here, tutorials and solutions, known issues and FAQ sections.

#### Screenshots or example usage

https://github.com/vtexdocs/helpcenter/assets/55800516/2372e7e9-724b-4f28-ad44-7b67efddf708

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2024-07-23 17:38 UTC, brunoamui approved these changes
LGTM

2024-10-17 19:23 UTC, PedroAntunesCosta requested changes
Precisamos atualizar com a main e resolver os conflitos.

2024-12-18 15:48 UTC, PedroAntunesCosta requested changes
Nos announcements o botão está alinhado à direita e o tooltip fica certinho alinhado com o botão.
![image](https://github.com/user-attachments/assets/2e237eed-0f90-41f1-96d2-2051c5a9353c)

Nos outros tipos de conteúdo, está alinhado à esquerda e o tooltip não está alinhado ao botão.
![image](https://github.com/user-attachments/assets/e8bae0f1-b732-4772-8499-51921e129e29)

Sugiro padronizar como está nos announcements, mas acho que não é super prioridade, se estiver difícil de achar o caminho, vamos mergear desalinhado e abrir uma issue pra solucionar depois.

2024-12-18 15:48 UTC, PedroAntunesCosta commented on src/messages/en.json
> +  "copy_link_button.text": "copy link",
```suggestion
  "copy_link_button.text": "Copy link",
```

2024-12-18 15:48 UTC, PedroAntunesCosta commented on src/messages/en.json
> +  "copy_link_button.tooltip": "copied!",
```suggestion
  "copy_link_button.tooltip": "Copied!",
```

2024-12-18 15:48 UTC, PedroAntunesCosta commented on src/messages/es.json
> +  "copy_link_button.text": "copiar link",
```suggestion
  "copy_link_button.text": "Copiar link",
```

2024-12-18 15:48 UTC, PedroAntunesCosta commented on src/messages/es.json
> +  "copy_link_button.tooltip": "copiado!",
```suggestion
  "copy_link_button.tooltip": "Copiado!",
```

2024-12-18 15:48 UTC, PedroAntunesCosta commented on src/messages/pt.json
> +  "copy_link_button.text": "copiar link",
```suggestion
  "copy_link_button.text": "Copiar link",
```

2024-12-18 15:48 UTC, PedroAntunesCosta commented on src/messages/pt.json
> +  "copy_link_button.tooltip": "copiado!",
```suggestion
  "copy_link_button.tooltip": "Copiado!",
```

2024-12-18 15:48 UTC, PedroAntunesCosta commented on src/pages/announcements/[slug].tsx
> +              </article>
O conteúdo está duplicado na página de announcements e eu acho que tem a ver com essas linhas adicionadas, já que nas outras páginas foi adicionada só uma linha com o componente.
![image](https://github.com/user-attachments/assets/287e82bb-5518-4185-b069-23d93346c09c)

2024-12-18 15:48 UTC, PedroAntunesCosta commented on src/components/tutorial-markdown-render/index.tsx
> +                    <CopyLinkButton />
Nos tutoriais a disposição do botão ficou esquisita. Ela ficou colada na linha que separa o h1. 
![image](https://github.com/user-attachments/assets/62e5aabe-50c5-46ca-ba78-a7f2fa706e58)

Comparação com como fica nos outros tipos de artigo:
![image](https://github.com/user-attachments/assets/7742fcd7-5dfb-4a60-bec4-2c1d0349517c)

Acho que é porque o componente foi inserido no renderizador ao invés de ficar no código da página como nos outros tipos. Sugiro tirar daqui e passar lá pro código da página.

2024-12-18 20:54 UTC, ricardoaerobr commented on src/components/tutorial-markdown-render/index.tsx
> +                    <CopyLinkButton />
Corrigido.

2024-12-19 19:36 UTC, PedroAntunesCosta approved these changes
Nice!

2024-12-19 19:42 UTC, merged