Fix docs paths validation
vtexdocs/helpcenter pull request #98
Opened 2024-09-04 23:40 UTC by PedroAntunesCosta

…to match new folder structure

#### What problem is this solving?

This `help-center-content` [PR](https://github.com/vtexdocs/help-center-content/pull/29) changes the repository's folder structure to match the portal's content architecture. This means we need to change the way we get/validate docs paths from github.

#### How should this be manually tested?

1. Run the portal locally from this branch, using `/preview?branch=edit-folder-structure`.
2. Try to access different articles.

2024-09-05 15:37 UTC, julia-rabello requested changes
Tutorials are working. I could also access an announcement, a known issue and a FAQ in the preview going directly to their URL. Examples:
- Announcement: https://deploy-preview-98--leafy-mooncake-7c2e5e.netlify.app/pt/announcements/2017-10-25-facebook-and-google-login-settings-have-changed
- KI: https://deploy-preview-98--leafy-mooncake-7c2e5e.netlify.app/pt/known-issues/12-digits-cardnumber-being-accepted-in-checkout-and-causing-stuck-transactions
- FAQ: https://deploy-preview-98--leafy-mooncake-7c2e5e.netlify.app/pt/faq/a-consulta-de-status-no-feed-do-gerenciamento-de-pedidos-e-por-appkey-ou

However, all of their listing pages seem to be empty, so there may be other files that need to be edited to retrieve docs for that list now that they're stored in different subfolders:

![image](https://github.com/user-attachments/assets/721477f6-49f9-4178-b343-9a3892ecd9a7)

2024-09-06 16:22 UTC, julia-rabello commented
Now that we merged https://github.com/vtexdocs/help-center-content/pull/29, I got this error while testing locally: _Named capturing groups are only available when targeting 'ES2018' or later.ts(1503)_

When I tried updated the `target` to es2018 in the `tsconfig.json` file, it worked: 
![screencapture-localhost-3000-pt-announcements-2024-09-06-13_20_16](https://github.com/user-attachments/assets/f44527a3-a22b-4b38-bc15-bd735f372181)

2024-09-06 18:07 UTC, julia-rabello approved these changes

2024-09-10 18:10 UTC, brunoamui approved these changes
LGTM

2024-09-10 18:11 UTC, merged